Rph chat integrated
RevRelay/RevRelay pull request #37
Opened 2022-01-06 20:14 UTC by RPHaynes

2022-01-06 21:38 UTC, LutherNa approved these changes
Approved, but please look at the suggestions before merging.

2022-01-06 21:38 UTC, LutherNa commented on src/App.js
> +			{/* Resnders Chat Box */}
```suggestion
			{/* Renders Chat Box */}
```

2022-01-06 21:38 UTC, LutherNa commented on src/Components/Client.js
> +	var [chatrooms, updateChatrooms] = useState([]);
I was under the impression that all useState ~~elements~~ ~~variables~~ _things_ are supposed to be declared as constant. 
```suggestion
	const [chatrooms, updateChatrooms] = useState([]);
```

2022-01-07 15:40 UTC, LutherNa approved these changes
I was all set to re-approved, but then I remembered I don't need to because new commits don't obliviate an old approval. Which is actually weird, I don't like that, you could commit anything and still use my approval. 
Regardless, Client.js could probably use more commenting and JSDocs, but otherwise I don't see any issues.

2022-01-07 15:47 UTC, Justin-Sherfey approved these changes

2022-01-07 15:52 UTC, LutherNa requested changes
This request cannot be merged until the corresponding merge to BackendChatroom goes through. Once that's done it's golden.

2022-01-07 15:55 UTC, LutherNa approved these changes

2022-01-07 15:55 UTC, merged