Groups pages settings
RevRelay/RevRelay pull request #43
Opened 2022-01-07 23:01 UTC by RPHaynes

2022-01-07 23:21 UTC, LutherNa requested changes
fix merge conflicts. and if you mess up the formatting Jennica will be rather cross.

2022-01-08 17:58 UTC, LutherNa requested changes
Tested with backend branch "main", frontend branch "groups-pages-settings" with main merged.
- Saving user page settings on a user page with nested posts causes an error on the backend due to saving the same post entity multiple times in the same transaction. 
- On the FriendsTab element, mapped friends do not have unique keys.
- FriendsTab has console.log() for debugging still enabled (_this should always be removed for merges to main_). 
- Adding a friend and joining a group return a 404 error, as those endpoints do not yet exist on main (and there are no pull requests open for backend changes, I checked). 
- Saving group page settings (even if there are no changes) causes the Settings button to turn into the Options button until I refresh the page. This also produces the following console error: 
`
MUI: The `value` provided to the Tabs component is invalid.
None of the Tabs' children match with "3".
You can provide one of the following values: 0, 1, 2. 
`
- Because the Join Chat button is on a dropdown off the Options button, I cannot attempt to join a chatroom for a page I own.
- Chat button doesn't seem to do anything, but I assume that's a WIP. 
- FriendsTab throwing the following error: 
`
react_devtools_backend.js:4045 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
`
- Please put all API queries in the API folder.

2022-01-09 21:21 UTC, RPHaynes commented
Merge conflicts fixed

2022-01-10 00:23 UTC, RPHaynes commented
Backend Pull request Opened

2022-01-10 15:19 UTC, Justin-Sherfey approved these changes

2022-01-10 15:27 UTC, JennicaLeClerc commented on src/Components/Page/FriendsTab.js
> +
Comment

2022-01-10 15:28 UTC, JennicaLeClerc commented on src/Components/Group/CreateGroup.js
> +
Comment

2022-01-10 15:28 UTC, JennicaLeClerc commented on src/Components/Group/AddMember.js
> +
Comment

2022-01-10 15:28 UTC, JennicaLeClerc commented on src/Components/Page/PageSetting.js
> +
Comment

2022-01-10 15:30 UTC, JennicaLeClerc reviewed
COMMENTS!!!!!

2022-01-10 15:39 UTC, LutherNa approved these changes

2022-01-10 15:50 UTC, AaronLitton approved these changes
Untested, but looks good to go

2022-01-10 16:19 UTC, JennicaLeClerc approved these changes
thanks

2022-01-10 16:19 UTC, merged